import "./globals.css";
import { StoreProvider } from "./Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          {/* this header is kept by me. we can customize header like this */}
          <header className=" bg-black text-white p-4">
            Header Component
          </header>
            {children}

            {/* this footer is kept by me. we can customize footer like this */}
          <footer className=" bg-black text-white p-4">Footer Component</footer>
        </StoreProvider>
      </body>
    </html>
  );
}
